site_name: 'Copper mail'
site_description: 'Copper email solution documentation'
site_author: 'Lanka Software Foundation'
site_url: 'https://copper.opensource.lk'

repo_name: 'LSFLK/Copper'
repo_url: 'https://github.com/LSFLK/Copper'

copyright: 'Copyright &copy; 2018 - 2019 Lanka Software Foundation'

nav:
    # - Copper mail: index.md
    - Overview: Overview.md
    - Features: userfeature.md
    - Technical Documentation: Structure.md
    - Prerequisites: Prerequisites.md
    - Installation version 6: Installation.md
    - Installation version 7: Installation-7.md
    - Initial Configuration: Configuration.md
    #- Client Configuration: CConfiguration.md
    - Backup & Restoration: Backups.md
    - Troubleshoot: troubleshoot.md
    - Centralized Supervision: Hub.md
    - Copper Hub Installation: HubInstallation.md
    - Copper Hub Features: Hubfeatures.md
    - Email security: issues.md
    - Next Features : future.md
    - LSF: lsf.md
    - FAQ: F&Q.md
    - Contact us: contactus.md
    
theme:
  name: 'material'
  palette:
    primary: 'amber'
    accent: 'amber'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/copper_logo.svg'
  language: 'en'
  favicon: 'images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true